rotacloud/rotacloud-node

package-lock.json, package.json, src/interfaces/availability.interface.ts, src/interfaces/query-params/availability-query-params.interface.ts, src/models/availability.model.ts, src/rotacloud.ts, src/services/availability.service.ts, src/services/index.ts
Adds an availability service for the `/availability` endpoint supporting a list method.
Also included doc comments for the availability query parameters; version bump and renamed `ApiAvailabilityDates` to `ApiAvailabilityDate` (singular) to better reflect it's type
=> Added availability service

src/interfaces/query-params/users-query-params.interface.ts
Removed unsupported query parameter for getting users.
For context `locations` is supported on the API but `location` (singular) is not
=> fix: query params for getting users

src/services/service.ts
Fixes a bug where initiating subsequent requests via the paging `link` header would cause query params to be duped.
Duplicate query params can be parsed as arrays on certain endpoints and so should be avoided.
Bug was due to the page links provided via the `link` header include all the query params made during the previous page request and so the original params object should be discarded when making a request for subsequent pages.
Also fixed up some types
=> fix: duping of query params in paged requests

package.json, src/services/shifts.service.ts
This fixes an issue with the current SDK where you can't publish or unpublish the shift.
Issue: missing `shifts` parameter in API call.
[RotaCloud API /shift_published](https://rotacloud.docs.apiary.io/#reference/0/shiftspublished/publish-shifts)
=> story/RWA-10 - Fixed issue with publish shift API in SDK

package.json, src/interfaces/day-note.interface.ts, src/models/day-note.model.ts
Issue: missing  `visible_employees` in ApiDayNote
=> story/RWA-26  - Added visible_employees in day note

package.json, src/interfaces/query-params/users-query-params.interface.ts
This PR adds a `location` property on existing `UsersQueryParams`. This fixes an issue related to [bug/RWA-857](https://rotacloud.atlassian.net/browse/RWA-857). As investigation shows that we can't properly filter out users by their start_date and end_date by using `locations` array as a param. We'd need to use the single `location` id to filter users properly.
=> bug/RWA-857 Adds `location` property on UsersQueryParams

package.json, src/interfaces/shift.interface.ts, src/models/shift.model.ts
Adding null type on shift user for supporting on amending shift with assigned user into an open shift. 
When editing a shift with assigned user, we should pass a null value on user in order for it to be processed by API as an open shift.
needed on :https://rotacloud.atlassian.net/browse/RWA-938
=> bug/RWA-938 - Shift: user property support null type

src/interfaces/query-params/leave-requests-query-params.interface.ts, src/services/leave-request.service.ts
Adds correct typing to the leave requests service and checked the supported query params on the leave request endpoint and narrowed the `status` field down.
Previously was using the `LeaveQueryParams` which are not used on the leave requests endpoint.
=> feat: update leave request typing

package-lock.json, package.json, src/interfaces/leave-date.interface.ts, src/interfaces/leave.interface.ts, src/models/leave.model.ts
https://rotacloud.atlassian.net/browse/RWA-1076
I want to enable the `hours `property of `ApiLeaveDate  `and `Leave `to support null as this would be used in creating separation on total hours if the hours method is yearly or daily
example request A: if yearly, hours should be set to null 
example request B: if daily, hours should be set to null
=> Update SDK ApiLeaveDate and Leave to support null hours

src/models/leave-type.model.ts
Fixed model not setting missing properties for `LeaveType`
=> fix: missing properties on leave type model

package-lock.json, package.json, src/services/leave.service.ts
ticket https://rotacloud.atlassian.net/browse/RWA-1126
dry_run is already added as option previously on  #72  but the options wasn't passed on the leave service-update
=> SDK: dry_run support for Leave Update

package.json, src/interfaces/query-params/toil-accruals-query-params.interface.ts
Recent changes on the API now does not require you to pass in a year before you could get the accrual records of an employee.
=> story/RWA-813 - Made `year` optional for toil accrual query param

.eslintrc.json, package-lock.json, package.json, src/services/attendance.service.ts, src/services/availability.service.ts, src/services/service.ts, src/services/shifts.service.ts
- Bumped dependencies to latest
- of note, TS has been updated to v5.1
- Fixed batched delete shifts
- Added support for batched updates to shifts
- Changed the implementation of the `update` method to support both updating a single shift and many shifts at once (similar to delete)
The signature of the `shifts.update` method has been changed to be more intuitive
e.g.
```ts
// Before this change; updating a shift:
const updatedShift = await client.shifts.update(1, {id: 1, published: true})
// Now becomes:
const updatedShift = await client.shifts.update({id: 1, published: true})
// And now supports multiple shift updates simultaneously via the same method:
const updatedShiftsResult = await client.shifts.update([
{ id: 1, published: true },
{ id: 2, start_time: 11111111 },
])
```
=> feat!: support batched shift updates

.github/workflows/check.yml, .github/workflows/publish.yml, package-lock.json, package.json, src/services/service.ts, src/services/shifts.service.ts
Adds support for pagination solely via the `limit`, `offset` and `total-count` headers and sets the new API query param `exclude_link_header=true` for all requests to prevent too large header payloads
=> bug/RWA-1189 - feat: simplify pagination by removing reliance on `link` header

package-lock.json, package.json, src/interfaces/query-params/index.ts, src/interfaces/query-params/internal-query-params.interface.ts, src/services/accounts.service.ts, src/services/attendance.service.ts, src/services/auth.service.ts, src/services/availability.service.ts, src/services/daily-budgets.service.ts, src/services/daily-revenue.service.ts, src/services/day-notes.service.ts, src/services/days-off.service.ts, src/services/groups.service.ts, src/services/leave-embargoes.service.ts, src/services/leave-request.service.ts, src/services/leave.service.ts, src/services/locations.service.ts, src/services/pins.service.ts, src/services/roles.service.ts, src/services/service.ts, src/services/settings.service.ts, src/services/shifts.service.ts, src/services/terminals-active.service.ts, src/services/terminals.service.ts, src/services/time-zone.service.ts, src/services/toil-accruals.service.ts, src/services/toil-allowance.service.ts, src/services/users-clock-in.service.ts, src/services/users.service.ts, todo.md
Adds proper type support for the `fields` option and the option is now only available on endpoints that support it.
Previously using fields would give the wrong types back and was error prone:
```ts
// Requesting a user with `fields` - TS would compile the following:
const user = await client.users.get(1, {fields: ["name", "bad-property"]})
// And `user` at this point would have the type `User` meaning this would compile even though `id` is actually undefined
console.log(user.id) // "undefined"
```
So not only was `fields` prone to typo bugs but the type returned would be wrong.
With this change both of these issues are solved:
```ts
// Only valid properties are now supported
const user = await client.users.get(1, {fields: ["name", "bad-property"]}) // -> error `"bad-property"` is not a …
```
=> story/RWA-867 - feat: stricter options and support for `fields` types

package-lock.json, package.json, src/interfaces/users-clocked-in.interface.ts, src/services/users-clock-in.service.ts
Add missing breaks_clocked to the UserClockedIn response
Makes some of the UserClockIn request optional. You don't need always need a shift ID because you can clock in without a shift. You don't need `terminal` if `method` is "mobile", and you don't need `location` if `method` is "terminal".
=> fix: fix types for clock in

package-lock.json, package.json, src/interfaces/sdk-config.interface.ts, src/rotacloud.ts, src/services/service.ts
Adds the ability to supply interceptors (currently based around axios' implementation) to the SDK config.
Example:
```ts
const client = new RotaCloud({
apiKey: '...',
accountId: 12345,
// Optional property with both `request` and `response` also being optional
interceptors: {
// Can supply as many as you like:
request: [
// Can supply a single callback method for handling successful requests
(req) => {
console.log('Request intercepted');
return req;
},
],
response: [
// Or supply an object specifying either or both of the success and error handlers
{
success: (res) => {
console.log("Response intercepted");
return res;
},
error: (res) => {
console.log("Handling error...");
return res;
}
],
},
});
```
As this is using axios interceptors under the hood the same types and implementation …
=> misc/interceptors - feat: add support for supplying custom interceptors for requests and responses

package-lock.json, package.json, src/interfaces/daily-revenue.interface.ts
I've modified the `DailyRevenue` to support null type for `labour_percentage` , `revenue_target` and `revenue_actual.`
=> story/RWA-1563 - Update dailyRevenue to support null values

src/interfaces/sdk-config.interface.ts, src/rotacloud.ts, src/services/accounts.service.ts, src/services/service.ts
Fixes a bug in which the retry configuration had stopped working; was being set for every request and wasn't attempting retries for `429` status codes.
With this change:
- axios-retry configuration is setup only when the SDK config has changed instead of every request made (including init of the `RotaCloud` class)
- axios-retry's underlying interceptor config is applied before all other interceptors
- This includes the custom error interceptor so that axios-retry works with the `AxiosError` type
- Previously this would be setup after all other interceptors
- axios-retry will now attempt to retry on `429` errors (`Too many requests`)
- SDKConfig is localized in each client. Previously all clients share the same SDKConfig but that limits us to only 1 baseURI. With this change we can now use …
=> misc/retry-fix - fix: axios-retry configuration and isolate SDKConfig to SDK instances

package-lock.json, package.json, src/services/service.ts
Adds a new option `maxResults` to the `Options` type with the intention of replacing and ultimately removing the `limit` parameter which has now been marked deprecated.
`limit` from an SDK callers point of view can be quite misleading and confusing.
Here is a scenario in which it might be used:
```ts
const client = new RotaCloud(...)
const results = await client.shifts.listAll(..., { limit: 10 })
console.log(results.length)
```
To someone reading above code without understanding how the SDK works under the hood I think they would expect the length of the results to be 10 at most however what actually happens is every shift is returned (that matches the query parameter) but fetched in pages of 10 results each making this a worse version of specifying no limit at all as if there were 100 …
=> feat: support for max results in list requests to replace `limit` option

README.md, src/client-builder.test.ts, src/client-builder.ts, src/endpoint.ts, src/interfaces/query-params/toil-allowance-query-params.interface.ts, src/interfaces/user.interface.ts, src/main.ts, src/ops.test.ts, src/ops.ts, src/service.ts, src/utils.ts
- Added features previously available in version one but were missed during the upgrade to v2
- Improved documentation for the `README.md` to get started and added many missing JSDoc comments
- Replaced Node specific packages to ensure compatibility with the web
- Batch ops: `deleteBatch` and `updateBatch`
- These were implicitly available for certain service methods in v1 now explicit callable ops in v2
- Op for listing by page: `listByPage`
- Previously available in v1 
- Updated `README` to reflect v2
- Add the SDK config to `OperationContext`
- Useful for custom operations that need reference to the provided config (in this case the `leave.create` method needs the account ID supplied by the config)
- `auth.get` op no longer insists on an entity ID (v1 behaviour)
-  `availability` …
=> feat/v2-webapp-compat - feat: add missing functionality; improved docs and web platform support

src/models/SDKError.model.ts, src/ops.test.ts, src/ops.ts, src/utils.ts
- Introduces v2 endpoint equivalent ops for listing
- This includes new methods for the ops: `list`, `listAll` and `listByPage`
- Endpoints marked as `v2` within the `EndpointEntityMap` will now use list v2 ops automatically instead of the v1 equivalents
- Endpoints marked as `v1` will continue to work as before
- A new `url` property was added to `SDKError` which have found to be useful information when debugging along with JSDoc comments for all public fields
- Removed redundant type for the `SDKError` constructor
=> feat/pagination-v2 - feat: add support for pagination in v2 endpoints

package-lock.json, package.json, src/ops.ts
Fixed op for v1 pagination where the request context used to base subsequent paged calls from was missing the URL and setup used for the first page call
=> misc/pagination-v1-fix - fix: paginated v1 calls

package-lock.json, package.json, src/service.ts
Fixes the service definition for `terminalActive` service which was left as a copy of the `terminal` service and missing the correct endpoint URL as well as the the right calls for the `customOperations`: `ping` and `launch`
=> bug/PLAT-630 - fix: terminalActive service with correct URL endpoint and types for custom ops

package-lock.json, package.json, src/endpoint.ts, src/interfaces/index.ts, src/interfaces/message.interface.ts, src/ops.ts, src/service.ts
Setup a service for "memos" (`/v1/messages`) with all associated types
This had been missed previously and is not a new endpoint but is now fully supported.
I've opted for aliasing the `create` op as `send` in keeping with the memo/message analogy (hoping to make using this service more intuitive)
- As part of this change I've made the `createOp` public to be used within custom methods so aliases are easier to set up
- Relaxed `CreateEntity` typing to insist on `object` rather than subsets of `Entity` within the `Endpoint` parameters and memos has shown this is not always the case.
=> feat/memos - feat: add support for the `/v1/messages` endpoint and associated types

package-lock.json, package.json, src/ops.ts, src/utils.ts
Added documentation via JSDoc comments for functions missing them and on existing doc comments that didn't elaborate enough in my view.
Also updated the `OpFunction` type to have a more descriptive return type name and support op param types with `number[]` showing the parameter name `"ids"` instead of `"entity"` for these op function signatures
=> docs: add missing doc comments and support `number[]` param type signatures in ops
