.eslintignore
.github/workflows/node.js.yml
package.json
src/services/accounts.service.ts

Minor updates for publishing to NPM
- License change
- Add linting step
- Ignore linting for version file
- Remove unnecessary conditional type

Minor updates

---

src/services/shifts.service.ts

An update to refactor the method signature of publish and publish method.

Refactored method signature for shift publish

---

package.json
src/interfaces/sdk-config.interface.ts
src/services/service.ts

This PR adds an undocumented way to add additional headers to requests

feat: ability to specify extra headers on requests

---

package.json
src/services/shifts.service.ts

Related Ticket - [Clear the (week/month) rota](https://rotacloud.atlassian.net/browse/RWA-912)

story/RWA-912: add batch delete - clearing shifts

---

package-lock.json
package.json
src/interfaces/index.ts
src/interfaces/query-params/index.ts
src/interfaces/query-params/toil-accruals-query-params.interface.ts
src/interfaces/query-params/toil-allowance-query-params.interface.ts
src/interfaces/toil-accrual.interface.ts
src/interfaces/toil-allowance.interface.ts
src/models/toil-accrual.model.ts
src/models/toil-allowance.model.ts
src/rotacloud.ts
src/services/index.ts
src/services/toil-accruals.service.ts
src/services/toil-allowance.service.ts

Ticket: https://rotacloud.atlassian.net/browse/RWA-1057
Adds methods for fetching data for:
TOIL accruals
TOIL allowances.
Delete for: TOIL accruals
Post fro: TOIL accruals
NB// deleting/creating won't be functional until the API for TOIL is no longer using dummy data.

Story/RWA-1057 - adds TOIL to SDK

---

src/models/index.ts

Missed export for the TOIL models from Ticket: https://rotacloud.atlassian.net/browse/RWA-1057

update the export for toil models

---

package-lock.json
package.json
src/services/leave-request.service.ts
src/services/leave.service.ts
src/services/service.ts

ticket https://rotacloud.atlassian.net/jira/software/projects/RWA/boards/72?selectedIssue=RWA-734
Added `?dry_run=true` in options . This is for calls where we want to assess errors or clashing leaves before committing to the action.

Story/RWA - 1061  Leave: add dry run to option

---

package-lock.json
package.json
src/rotacloud.ts
src/services/leave-types.service.ts

Adds a new service for interacting with the `/leave_types` endpoint

story/RWA-1088 - feat: LeaveTypesService

---

package.json
src/models/toil-allowance.model.ts
src/services/toil-accruals.service.ts

Fixes an issue with TOILAllowance class where the wrong value is being assigned to its property.
This also removes 'date' as a required property when creating TOIL accrual as it's optional

story/RWA-807 Fixes for TOIL accrual

---

package.json
src/models/toil-allowance.model.ts
src/services/toil-accruals.service.ts

* Merge pull request #50 from rotacloud/develop (#52)
* wip leave models
* version bump
* Added visible_employees in day note
* reverted package-lock json changes
* version bump
* feat: ability to specify extra headers on requests (#56)
* added a new parameter for user endpoint
* v bump
* bug/RWA-938 - Shift: user property support null type
* feat: update leave request typing (#60)
* misc/model-exports - feat: allow models to be imported from root of package (#59)
* feat: export models at root of package
* build: remove unused dependency
* handle errors in response interceptor
* missed log
* remove altered availability path
was being used for testing
* PR comments - improve parse
* return type for parser
* variable names
* models index
* improve axios error typing
* re-add optional …

Develop -> Main (#85)

---

package.json
src/services/service.ts

This adds `offset` as an option so client can fetch specific pages from the endpoint.

story/RWA-1155 - Add support for `offset` param for services for getting pages

---

package.json
src/interfaces/leave-date.interface.ts
src/interfaces/leave-request.interface.ts
src/interfaces/leave.interface.ts

https://rotacloud.atlassian.net/browse/RWA-1130
support sending hours for leave request

RWA-1130: Employee adding hours to leave request 

---

package-lock.json
package.json
src/interfaces/index.ts
src/interfaces/terminal.interface.ts
src/interfaces/time-zone.interface.ts
src/rotacloud.ts
src/services/index.ts
src/services/time-zone.service.ts

Adds Time Zone service and related interfaces. 
Added missing optional type from Terminal interface. 
Followed current pattern for other services.

Tma 85/time zone endpoint

---

package-lock.json
package.json
src/interfaces/role-rate.interface.ts
src/interfaces/user.interface.ts

Fixes the typing for the user role rates

Fixed typing for role_rate of a user

---

package-lock.json
package.json
src/interfaces/user.interface.ts

I've modified the `User` type to include `permissions`, which is an optional string array.

TMA-116: Added permissions to user type

---

package-lock.json
package.json
src/interfaces/terminal.interface.ts

Updates the `Terminal` type to include the new property `default_location`

misc/location-update - adds support for Terminal default_location

---

package-lock.json
package.json
src/services/toil-accruals.service.ts
src/services/toil-allowance.service.ts

Fixes import paths missing a file extension required for ESM

fix: imports for ESM in toil services

---

package-lock.json
package.json
src/interfaces/document.interface.ts
src/interfaces/index.ts
src/interfaces/query-params/documents-query-params.interface.ts
src/rotacloud.ts
src/services/documents.service.ts

Initial setup and type definitions for interacting with the `/documents` API endpoint

misc/documents - feat: Documents service

---

package-lock.json
package.json
src/interfaces/role.interface.ts

I've modified the Role to support null type for colour .

bug/RWA-1809 Update role colour to support null values

---

package-lock.json
package.json
src/services/shifts.service.ts

Fixed the interface for acknowledging shifts

story/DU-17: updated acknowledge interface

---

package.json
src/interfaces/drop-request.interface.ts
src/interfaces/swap-request.interface.ts
src/services/shifts.service.ts

Updated the sdk to include updateSwap and updateDrop alongside interfaces for both as part of DU-119

 DU-119 Move shifts to global redux store

---

src/interfaces/user.interface.ts

Updated the user interface in line with DU-134

DU-134 - update user interface

---

package-lock.json
package.json
src/service.ts

Small bug fix to improve compatibility with v1 SDK

fix/role-ops - fix: add missing role ops "create" and "update"

---

package-lock.json
package.json
src/ops.ts

Fixes the payload used in the `deleteBatchOp`

misc/batch-delete-payload fix: payload used to deleteBatch

---

package-lock.json
package.json
src/endpoint.ts
src/interfaces/day-note.interface.ts
src/service.ts

Updates SDK to support for day notes v2
- added subservice v2 
- added new interface

SCH-259 feat: add v2 support for dayNotes endpoint

---

package-lock.json
package.json
src/endpoint.ts
src/interfaces/index.ts
src/interfaces/user-v2.interface.ts
src/service.ts

Updated the sdk to include the new userV2 endpoint
Added as necessary to service.ts and endpoint.ts including new UserV2 interface

update sdk to include userV2
